server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/windows_db?currentSchema=public
    username: ${WINDOW_DB_LOGIN}
    password: ${WINDOW_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
    database: postgresql
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: window--group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: ru.pin36bik.dto.WindowLocationRequestEvent
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: ${JWT_SECRET}
  access-ttl: ${JWT_ACCESS_TTL}
  refresh-ttl: ${JWT_REFRESH_TTL}