spring:
  cloud:
    gateway:
      routes:
        - id: microservice-user-management
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/**
          filters:
            - TokenRelay

        - id: microservice-user-management
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/**

        - id: microservice-window-management
          uri: http://localhost:8083
          predicates:
            - Path=/api/windows/**
          filters:
            - TokenRelay

        - id: microservice-analytics
          uri: http://localhost:8084
          predicates:
            - Path=/api/analytics/**
          filters:
            - TokenRelay

        - id: microservice-notifications
          uri: http://localhost:8085
          predicates:
            - Path=/api/notifications/**
          filters:
            - TokenRelay

        - id: microservice-presets
          uri: http://localhost:8086
          predicates:
            - Path=/api/presets/**
          filters:
            - TokenRelay

        - id: microservice-visual-content
          uri: http://localhost:8087
          predicates:
            - Path=/api/visual/**
          filters:
            - TokenRelay

        - id: microservice-weather
          uri: http://localhost:8088
          predicates:
            - Path=/api/weather/**
          filters:
            - TokenRelay
