spring:
  application:
    name: smart-windows
  kafka:
    bootstrap-servers: localhost:9092
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8079
