spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_windows
    username: ${BD_LOGIN}
    password: ${BD_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60000
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      name: tuple-topic

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    operationsSorter: alpha
  api-docs:
    path: /api-docs
  show-actuator: true