#!/bin/bash
set -ex

sleep 5

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER "$USER_DB_LOGIN" WITH PASSWORD '$USER_DB_PASSWORD';
  CREATE USER "$WINDOW_DB_LOGIN" WITH PASSWORD '$WINDOW_DB_PASSWORD';
  CREATE USER "$WEATHER_DB_LOGIN" WITH PASSWORD '$WEATHER_DB_PASSWORD';
  CREATE USER "$PRESETS_DB_LOGIN" WITH PASSWORD '$PRESETS_DB_PASSWORD';
  CREATE USER "$ANALYTICS_DB_LOGIN" WITH PASSWORD '$ANALYTICS_DB_PASSWORD';

  CREATE DATABASE users_db OWNER "$USER_DB_LOGIN";
  CREATE DATABASE windows_db OWNER "$WINDOW_DB_LOGIN";
  CREATE DATABASE weather_db OWNER "$WEATHER_DB_LOGIN";
  CREATE DATABASE presets_db OWNER "$PRESETS_DB_LOGIN";
  CREATE DATABASE analytics_db OWNER "$ANALYTICS_DB_LOGIN";

  GRANT ALL PRIVILEGES ON DATABASE users_db TO "$USER_DB_LOGIN";
  GRANT ALL PRIVILEGES ON DATABASE windows_db TO "$WINDOW_DB_LOGIN";
  GRANT ALL PRIVILEGES ON DATABASE weather_db TO "$WEATHER_DB_LOGIN";
  GRANT ALL PRIVILEGES ON DATABASE presets_db TO "$PRESETS_DB_LOGIN";
  GRANT ALL PRIVILEGES ON DATABASE analytics_db TO "$ANALYTICS_DB_LOGIN";
EOSQL